USE bank;

DESC Product;
SELECT * FROM Product;

ALTER TABLE Product
ADD Detail VARCHAR(1000) NOT NULL;

ALTER TABLE Product
MODIFY COLUMN detail VARCHAR(1000) AFTER rate;

ALTER TABLE Product
MODIFY COLUMN detail VARCHAR(1000) NOT NULL;

ALTER TABLE Product
MODIFY COLUMN sav_method VARCHAR(20) AFTER summary;

ALTER TABLE Product
MODIFY COLUMN exp_period int(11) AFTER sav_method;


DESC User;


USE mydb6;

DESC Board;
SELECT * FROM Board;

DESC Reply;
SELECT * FROM Reply;